<?php
return
[

      'costume'=>[
            'images'=>[
                          [
                           'width'=>275,
                          'height'=>275
                          ],
                            [
                                'width'=>600,
                                'height'=>400
                            ],
                [
                    'width'=>275,
                    'height'=>200
                ],
]]
];
